### ISSUE TITLE
Provide a way to continue and redo Move-Less mode navigation from a location

### ISSUE THREAD

**Issue by resolritter** [anschnapp/move-less#2]
#### Possible use cases:

- Save folds before exiting a file and then restore the fold configuration when coming back. I think this is low priority but would be nice.
`:call MoveLess#Save`
`:call MoveLess#Restore`
- Modification:
     - Pop the fold configuration from a stack. Enables MoveLess mode.
`:call MoveLess#Pop`
     - Modify it as he wants it with H h J K...
     - Put it back into the stack. This exits the fold and puts the configuration in the stack.
`:call MoveLess#Push`
- Switch between different folds configuration in the stack.
`:call MoveLess#EnableFold(2) -- enables the second fold in the stack`.

The main benefits would be to quickly switch to navigate on sections of the file.

#### Example workflow:
- `:call MoveLessMode() and navigate a bit in the top of the file. [FOLD1]`
- `:call MoveLess#Push() to put the fold in the stack [FOLD1]. Now I want to go to the bottom of the file.`
- `:call MoveLess#EnableFold(2) -- loads the second fold configuration and navigate to the bottom of the file. [FOLD2]`
- `Navigate, stop. Make some edits, then :call MoveLess#Pop [FOLD1]. Now I'm back at the top of the file in MoveLess mode and my bottom configuration [FOLD2] is still saved in the stack.`

What do you think? I didn't use fold much before finding this plugin, but the workflow seems useful.

**Comment by anschnapp** [comment]
saving on exiting make sense to me.
but for now i hold every information inside the buffer scope. if someone close the buffer the information would all be gone. and i don't know it i want to save stuff outside the buffer scope.

the stack approach is quite interesting.
but i don't be sure if i get your scenario correctly.

1. you navigate a bit at the top of the file {FOLD1}
2. you put it on the stack (and exit the move less mode i guess)
you go to the buttom of the file (via move-less mode or with normal navigation)
3. you load the second fold. but what is the second fold i thought you have only FOLD1 on the stack right now
4. I guess you have now a move less mode you can continue on at the top and the botton.
But is it a common case that I will continue a old move less mode with the old folding. (i really don't know)
I always thought that it's a one time navigation but without moving the cursor and nicer key bindings (also nicer abort of the navigation) then without the mode.

Do you have faced such situation while you editing where it would be handy to have such a stack?

**Comment by resolritter** [comment]
I had this idea because there's the "stop" mode for MoveLess mode which retains the folding. So there could be a "continue" mode too where you can get back at navigating after exiting. **I think there's value in not only navigating, but interactively managing folds hi the way provided by this plugin.**

That being said I haven't practiced situations where this would be handy to use. I'll try to implement the feature in the next days and see it it's really useful or not. Thanks for the comments.

**Comment by anschnapp** [comment]
@reaysawa yeah i would find it also really interesting how this works in practice and if it's handy.

I also think a little bit of you idea.
maybe just as a brainstorming what would you think about the following adjustment or additions of your idea:

every folding is saved, the user don't have to give in a extra command/keymapping for it
there is a `continue last move less mode` command
there is a `continue move less mode with alias``alias` command

the last move less mode is "stored" in alias 0 the one before it in 1.. .and so on until 9 (similar to the register names for yank register).

the user has also the option to save a move less mode with a given alias as a extra command. the alias should be a character then and not a number (kind of similar to yank into a register name)
so the user could say `store current move less mode as alias p`

so it's more a map of alias stored move-less modes then a set.

maybe you could even support two type of actions for a stored move less mode.
1. continue the move less mode (that's what's i meant in the examples above)
2. toggle belonging folding of the stored move less mode, without jumping to it and without starting move less mode:
This could be a good tool for you idea of creating foldings with move less mode for the sake of the folding itself and not for navigation.

as i said just for brainstorming purpose.

Thanks for bringing a new creative process into this project. 😃

**Comment by resolritter** [comment]
I now think that the whole idea of stacks is not only difficult to get right, but Vim already come with good support for jumping to places of the file with marks. So you could just mark the top of the file, jump to it, activate MoveLess mode in a custom function and them exit when you're done.

There is a good plugin for managing marks called [vim-signature](https://github.com/kshenoy/vim-signature), and there are some plugins for storing and recovering the folds using Vim's builtin commands `:mkview` and `:loadview`, like [vim-stay](https://github.com/zhimsel/vim-stay).

I think marks are a more solid way to do jumping instead of remembering "the stack" positions. All in all, now that I've thought more about it, it seems possible to do what I was planning in conjunction with other plugins. 

```
1.1 Jump to a pre-existing mark and start MovelessMode.
or
1.2 Jump to a place in the file and automatically mark it using vim-signature.
2. Enter MoveLess mode.
3. Browse, browse, escape, jump to somewhere else...
4. Your folds would be saved using the built-in commands or vim-stay.
```

The only remaining pieces would be
- Move-less needs to be able to continue folding a previously escaped fold
- Move-less can't undo other folds or the previous move-less folds when starting it again. As I recall, last time I tested, my previous move-less mode folds disappeared when I started browsing again at the top of the file. Does that happen to you too?

**Comment by anschnapp** [comment]
interesting setup you choose. would like to see a screencast if this works out for you ;)

about the two remaining pieces:
1. I agree we should have such a mode. Would be nice if you can make a new explicit feature ticket for this. I can assign it to you if you want to implement it. Otherwise I will take it up (will take some time because of time constraints on my side)
2. The folding should disapear if you move yourself outside the fold. This effect is per purpose. The navigation has ended and the folding was just a means to an end.
But there is already the possibility of stopping the mode with p for (permanent fold), then the folding should remain until you start a new move less mode. So, I guess there's no need for a ticket here.

I will close this ticket because the described feature will not be implemented in that way. But as I described there could be one (or maybe more) tickets be generated from this discussion.
